# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia

notifications:
  email: false

os:
  - linux

julia:
  - 1.4
  - 1.5
  - nightly

branches:
  only:
  - master
  - develop

notifications:
    email: false

arch:
  - x64

cache:
  directories:
    - ~/.julia/artifacts

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.5
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip

after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
